{
    "data_version": "4.0",
    "data_type": "CVE",
    "data_format": "MITRE",
    "CVE_data_meta": {
        "ID": "CVE-2025-2953",
        "ASSIGNER": "cna@vuldb.com",
        "STATE": "PUBLIC"
    },
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "A vulnerability, which was classified as problematic, has been found in PyTorch 2.6.0+cu124. Affected by this issue is the function torch.mkldnn_max_pool2d. The manipulation leads to denial of service. An attack has to be approached locally. The exploit has been disclosed to the public and may be used."
            },
            {
                "lang": "deu",
                "value": "Eine problematische Schwachstelle wurde in PyTorch 2.6.0+cu124 entdeckt. Es geht hierbei um die Funktion torch.mkldnn_max_pool2d. Dank Manipulation mit unbekannten Daten kann eine denial of service-Schwachstelle ausgenutzt werden. Der Angriff muss lokal passieren. Der Exploit steht zur \u00f6ffentlichen Verf\u00fcgung."
            }
        ]
    },
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "Denial of Service",
                        "cweId": "CWE-404"
                    }
                ]
            }
        ]
    },
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "vendor_name": "n/a",
                    "product": {
                        "product_data": [
                            {
                                "product_name": "PyTorch",
                                "version": {
                                    "version_data": [
                                        {
                                            "version_affected": "=",
                                            "version_value": "2.6.0+cu124"
                                        }
                                    ]
                                }
                            }
                        ]
                    }
                }
            ]
        }
    },
    "references": {
        "reference_data": [
            {
                "url": "https://vuldb.com/?id.302006",
                "refsource": "MISC",
                "name": "https://vuldb.com/?id.302006"
            },
            {
                "url": "https://vuldb.com/?ctiid.302006",
                "refsource": "MISC",
                "name": "https://vuldb.com/?ctiid.302006"
            },
            {
                "url": "https://vuldb.com/?submit.521279",
                "refsource": "MISC",
                "name": "https://vuldb.com/?submit.521279"
            },
            {
                "url": "https://github.com/pytorch/pytorch/issues/149274",
                "refsource": "MISC",
                "name": "https://github.com/pytorch/pytorch/issues/149274"
            },
            {
                "url": "https://github.com/pytorch/pytorch/issues/149274#issue-2923122269",
                "refsource": "MISC",
                "name": "https://github.com/pytorch/pytorch/issues/149274#issue-2923122269"
            }
        ]
    },
    "credits": [
        {
            "lang": "en",
            "value": "Default436352 (VulDB User)"
        }
    ],
    "impact": {
        "cvss": [
            {
                "version": "3.1",
                "baseScore": 3.3,
                "vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L",
                "baseSeverity": "LOW"
            },
            {
                "version": "3.0",
                "baseScore": 3.3,
                "vectorString": "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L",
                "baseSeverity": "LOW"
            },
            {
                "version": "2.0",
                "baseScore": 1.7,
                "vectorString": "AV:L/AC:L/Au:S/C:N/I:N/A:P"
            }
        ]
    }
}