{
    "data_version": "4.0",
    "data_type": "CVE",
    "data_format": "MITRE",
    "CVE_data_meta": {
        "ID": "CVE-2024-8088",
        "ASSIGNER": "cna@python.org",
        "STATE": "PUBLIC"
    },
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "There is a HIGH severity vulnerability affecting the CPython \"zipfile\"\nmodule affecting \"zipfile.Path\". Note that the more common API \"zipfile.ZipFile\" class is unaffected.\n\n\n\n\n\nWhen iterating over names of entries in a zip archive (for example, methods\nof \"zipfile.Path\" like \"namelist()\", \"iterdir()\", etc)\nthe process can be put into an infinite loop with a maliciously crafted\nzip archive. This defect applies when reading only metadata or extracting\nthe contents of the zip archive. Programs that are not handling\nuser-controlled zip archives are not affected."
            }
        ]
    },
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "CWE-835 Loop with Unreachable Exit Condition ('Infinite Loop')",
                        "cweId": "CWE-835"
                    }
                ]
            }
        ]
    },
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "vendor_name": "Python Software Foundation",
                    "product": {
                        "product_data": [
                            {
                                "product_name": "CPython",
                                "version": {
                                    "version_data": [
                                        {
                                            "version_affected": "<=",
                                            "version_name": "0",
                                            "version_value": "3.13.0"
                                        }
                                    ]
                                }
                            }
                        ]
                    }
                }
            ]
        }
    },
    "references": {
        "reference_data": [
            {
                "url": "https://mail.python.org/archives/list/security-announce@python.org/thread/GNFCKVI4TCATKQLALJ5SN4L4CSPSMILU/",
                "refsource": "MISC",
                "name": "https://mail.python.org/archives/list/security-announce@python.org/thread/GNFCKVI4TCATKQLALJ5SN4L4CSPSMILU/"
            },
            {
                "url": "https://github.com/python/cpython/pull/122906",
                "refsource": "MISC",
                "name": "https://github.com/python/cpython/pull/122906"
            },
            {
                "url": "https://github.com/python/cpython/issues/122905",
                "refsource": "MISC",
                "name": "https://github.com/python/cpython/issues/122905"
            },
            {
                "url": "https://github.com/python/cpython/commit/795f2597a4be988e2bb19b69ff9958e981cb894e",
                "refsource": "MISC",
                "name": "https://github.com/python/cpython/commit/795f2597a4be988e2bb19b69ff9958e981cb894e"
            },
            {
                "url": "https://github.com/python/cpython/commit/8c7348939d8a3ecd79d630075f6be1b0c5b41f64",
                "refsource": "MISC",
                "name": "https://github.com/python/cpython/commit/8c7348939d8a3ecd79d630075f6be1b0c5b41f64"
            },
            {
                "url": "https://github.com/python/cpython/commit/dcc5182f27c1500006a1ef78e10613bb45788dea",
                "refsource": "MISC",
                "name": "https://github.com/python/cpython/commit/dcc5182f27c1500006a1ef78e10613bb45788dea"
            },
            {
                "url": "https://github.com/python/cpython/commit/e0264a61119d551658d9445af38323ba94fc16db",
                "refsource": "MISC",
                "name": "https://github.com/python/cpython/commit/e0264a61119d551658d9445af38323ba94fc16db"
            }
        ]
    },
    "generator": {
        "engine": "Vulnogram 0.2.0"
    },
    "source": {
        "discovery": "UNKNOWN"
    },
    "credits": [
        {
            "lang": "en",
            "value": "Jason R. Coombs"
        },
        {
            "lang": "en",
            "value": "Seth Larson"
        }
    ],
    "impact": {
        "cvss": [
            {
                "attackComplexity": "LOW",
                "attackVector": "NETWORK",
                "availabilityImpact": "HIGH",
                "baseScore": 7.5,
                "baseSeverity": "HIGH",
                "confidentialityImpact": "NONE",
                "integrityImpact": "NONE",
                "privilegesRequired": "NONE",
                "scope": "UNCHANGED",
                "userInteraction": "NONE",
                "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "version": "3.1"
            }
        ]
    }
}