{
    "data_version": "4.0",
    "data_type": "CVE",
    "data_format": "MITRE",
    "CVE_data_meta": {
        "ID": "CVE-2024-21506",
        "ASSIGNER": "report@snyk.io",
        "STATE": "PUBLIC"
    },
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "Versions of the package pymongo before 4.6.3 are vulnerable to Out-of-bounds Read in the bson module. Using the crafted payload the attacker could force the parser to deserialize unmanaged memory. The parser tries to interpret bytes next to buffer and throws an exception with string. If the following bytes are not printable UTF-8 the parser throws an exception with a single byte."
            }
        ]
    },
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "Out-of-bounds Read",
                        "cweId": "CWE-125"
                    }
                ]
            }
        ]
    },
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "vendor_name": "n/a",
                    "product": {
                        "product_data": [
                            {
                                "product_name": "pymongo",
                                "version": {
                                    "version_data": [
                                        {
                                            "version_affected": "<",
                                            "version_name": "0",
                                            "version_value": "4.6.3"
                                        }
                                    ]
                                }
                            }
                        ]
                    }
                }
            ]
        }
    },
    "references": {
        "reference_data": [
            {
                "url": "https://security.snyk.io/vuln/SNYK-PYTHON-PYMONGO-6370597",
                "refsource": "MISC",
                "name": "https://security.snyk.io/vuln/SNYK-PYTHON-PYMONGO-6370597"
            },
            {
                "url": "https://gist.github.com/keltecc/62a7c2bf74a997d0a7b48a0ff3853a03",
                "refsource": "MISC",
                "name": "https://gist.github.com/keltecc/62a7c2bf74a997d0a7b48a0ff3853a03"
            },
            {
                "url": "https://github.com/mongodb/mongo-python-driver/commit/56b6b6dbc267d365d97c037082369dabf37405d2",
                "refsource": "MISC",
                "name": "https://github.com/mongodb/mongo-python-driver/commit/56b6b6dbc267d365d97c037082369dabf37405d2"
            }
        ]
    },
    "credits": [
        {
            "lang": "en",
            "value": "Vladimir Cherepanov"
        }
    ],
    "impact": {
        "cvss": [
            {
                "version": "3.1",
                "attackVector": "LOCAL",
                "attackComplexity": "HIGH",
                "privilegesRequired": "NONE",
                "userInteraction": "REQUIRED",
                "scope": "CHANGED",
                "confidentialityImpact": "LOW",
                "integrityImpact": "LOW",
                "availabilityImpact": "LOW",
                "baseScore": 5.2,
                "baseSeverity": "MEDIUM",
                "vectorString": "CVSS:3.1/AV:L/AC:H/PR:N/UI:R/S:C/C:L/I:L/A:L/E:P"
            }
        ]
    }
}