{
    "CVE_data_meta": {
        "ASSIGNER": "cve@mitre.org",
        "ID": "CVE-2018-25111",
        "STATE": "PUBLIC"
    },
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "product": {
                        "product_data": [
                            {
                                "product_name": "n/a",
                                "version": {
                                    "version_data": [
                                        {
                                            "version_value": "n/a"
                                        }
                                    ]
                                }
                            }
                        ]
                    },
                    "vendor_name": "n/a"
                }
            ]
        }
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "django-helpdesk before 1.0.0 allows Sensitive Data Exposure because of os.umask(0) in models.py."
            }
        ]
    },
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "n/a"
                    }
                ]
            }
        ]
    },
    "references": {
        "reference_data": [
            {
                "url": "https://github.com/django-helpdesk/django-helpdesk/pull/1120",
                "refsource": "MISC",
                "name": "https://github.com/django-helpdesk/django-helpdesk/pull/1120"
            },
            {
                "url": "https://github.com/django-helpdesk/django-helpdesk/releases/tag/v1.0.0",
                "refsource": "MISC",
                "name": "https://github.com/django-helpdesk/django-helpdesk/releases/tag/v1.0.0"
            },
            {
                "url": "https://github.com/django-helpdesk/django-helpdesk/issues/591",
                "refsource": "MISC",
                "name": "https://github.com/django-helpdesk/django-helpdesk/issues/591"
            }
        ]
    }
}