{
    "data_type": "CVE",
    "data_format": "MITRE",
    "data_version": "4.0",
    "CVE_data_meta": {
        "ID": "CVE-2020-1733",
        "ASSIGNER": "secalert@redhat.com",
        "STATE": "PUBLIC"
    },
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "vendor_name": "Red Hat",
                    "product": {
                        "product_data": [
                            {
                                "product_name": "Ansible",
                                "version": {
                                    "version_data": [
                                        {
                                            "version_value": "2.7.17 and prior"
                                        },
                                        {
                                            "version_value": "2.8.9 and prior"
                                        },
                                        {
                                            "version_value": "2.9.6 and prior"
                                        }
                                    ]
                                }
                            }
                        ]
                    }
                }
            ]
        }
    },
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "CWE-377"
                    }
                ]
            }
        ]
    },
    "references": {
        "reference_data": [
            {
                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1733",
                "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1733",
                "refsource": "CONFIRM"
            },
            {
                "url": "https://github.com/ansible/ansible/issues/67791",
                "name": "https://github.com/ansible/ansible/issues/67791",
                "refsource": "MISC"
            }
        ]
    },
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "A race condition flaw was found in Ansible Engine 2.7.17 and prior, 2.8.9 and prior, 2.9.6 and prior when running a playbook with an unprivileged become user. When Ansible needs to run a module with become user, the temporary directory is created in /var/tmp. This directory is created with \"umask 77 && mkdir -p <dir>\"; this operation does not fail if the directory already exists and is owned by another user. An attacker could take advantage to gain control of the become user as the target directory can be retrieved by iterating '/proc/<pid>/cmdline'."
            }
        ]
    },
    "impact": {
        "cvss": [
            [
                {
                    "vectorString": "5/CVSS:3.1/AV:L/AC:H/PR:L/UI:R/S:C/C:L/I:L/A:L",
                    "version": "3.0"
                }
            ]
        ]
    }
}